# Site settings
title: Nomad Equipment
email: contact@nomad.equipment
description: "Best gear for digital nomads and travellers."
baseurl: ""
url: "http://nomad.equipment"
twitter_username: matti_sg

collections:
  app:
    output: true

defaults:
  -
    scope:
      path: ""  # means "all files"
      type: "app" # targets a collection
    values:
      layout: "app"
